using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace DDMAutoGUI.utilities
{

    public class RunCalibResult
    {
        public bool success { get; set; }
        public string message { get; set; }
        public DateTime time { get; set; }
        public string motorName { get; set; }
        public float sf1 { get; set; }
        public float sf2 { get; set; }
    }


    public class FlowCalibrationManager
    {

        public FlowCalibrationManager() { }

        public async Task<RunCalibResult> RunDispenseForManualCalibration(
            CellSettings settings,
            LocalData localData,
            string motorName)
        {

            /// <summary>
            /// Runs dispense routine for given motor size ONCE. Returns results object.
            /// If successful, returns new pressure settings. Does basic validation, does not save.
            /// Iteration handled in calling function if unsuccessful or if visual inspection fails.
            /// 
            /// RUNS THE ROBOT AROUND AND DISPENSES CA.
            /// 
            /// DOES NOT SAVE TO FILE.
            /// 
            /// </summary>

            RunCalibResult result = new RunCalibResult();

            result.success = false;
            result.message = "";

            if (App.GUI_SIM_MODE)
            {
                await Task.Delay(1000); // simulate time delay
                result.success = true;
                result.time = DateTime.Now;
                result.motorName = motorName;
                result.sf1 = 0.99f;
                result.sf2 = 1.02f;
                result.message = "Success (!) SIMULATED (!)";
                return result;
            }

            try
            {
                string response;
                float x, t;
                CSMotor motorSettings = App.SettingsManager.GetMotorSettingsFromName(motorName);

                // Enable power and home
                await App.ControllerManager.EnablePower();
                await App.ControllerManager.Home();

                // Move to load
                x = settings.ddm_common.load.x.Value;
                t = settings.ddm_common.load.t.Value;
                await App.ControllerManager.MoveJ(x, t);

                // Move to detect if correct CA catch tool is loaded
                //x = motorSettings.calib_tool_test.x.Value;
                //t = motorSettings.calib_tool_test.t.Value;
                //await App.ControllerManager.MoveJ(x, t);

                //// Get height to verify correct tool is loaded
                //response = await App.ControllerManager.MeasureHeightSingle();
                //string[] responseArray = response.Split(" ");
                //if (responseArray.Length < 2 || !float.TryParse(responseArray[1], out _))
                //{
                //    throw new Exception($"Calibration failed: Unexpected response format from height measurement: '{response}'"); // autogenerated... ?
                //}
                //float height = float.Parse(responseArray[1]);

                //// Test height to verify correct tool is loaded
                //float diffSurface = settings.calib_surface_height.Value - height;
                //float diffTool = settings.calib_tool_height.Value - height;
                //float diffMax = settings.calib_tool_max_diff.Value;

                //if (Math.Abs(diffSurface) < diffMax)
                //{
                //    // if height is close to surface height, no tool is loaded
                //    throw new Exception($"Calibration failed: No tool detected");
                //}
                //else if (Math.Abs(diffTool) < diffMax)
                //{
                //    // if height is close to tool height, correct tool is loaded and continue with calibration
                //}
                //else
                //{
                //    // if height is not close to either, something else is wrong, abort
                //    throw new Exception($"Calibration failed: Unexpected height measurement ({height})");
                //}

                // Set pressures based on current calib
                LDMotorCalib oldCalib = App.LocalDataManager.GetCalibFromMotorName(localData, motorName);
                float? oldPressure1 = oldCalib.sys_1_pressure;
                float? oldPressure2 = oldCalib.sys_2_pressure;
                if (oldPressure1 != null)
                {
                    Debug.Print($"Setting pressure for system 1 ({settings.dispense_system.sys_1_contents}) to {oldPressure1.Value:F3} psi");
                    response = await App.ControllerManager.SetRegPressure(1, oldPressure1.Value);
                }
                else
                {
                    Debug.Print($"No pressure change for system 1 ({settings.dispense_system.sys_1_contents})");
                }
                if (oldPressure2 != null)
                {
                    Debug.Print($"Setting pressure for system 2 ({settings.dispense_system.sys_2_contents}) to {oldPressure2.Value:F3} psi");
                    response = await App.ControllerManager.SetRegPressure(2, oldPressure2.Value);
                }
                else
                {
                    Debug.Print($"No pressure change for system 2 ({settings.dispense_system.sys_2_contents})");
                }
                Debug.Print("Waiting for pressures to settle...");
                response = await App.ControllerManager.WaitBothRegPressures(10);
                await Task.Delay(1000);
                Debug.Print("Pressures settled");
                Debug.Print("Zeroing flow sensors...");
                response = await App.ControllerManager.SetZeroShift(3);
                Debug.Print("Flow sensors zeroed");
                Debug.Print("Pressures set");

                // Dispense to ring
                int sysID = motorSettings.shot_settings.id_sys_num.Value;
                int sysOD = motorSettings.shot_settings.od_sys_num.Value;
                float xID = motorSettings.id_disp.x.Value;
                float tID = motorSettings.id_disp.t.Value;
                float xOD = motorSettings.od_disp.x.Value;
                float tOD = motorSettings.od_disp.t.Value;
                float targetTimeID = motorSettings.shot_settings.id_target_vol.Value / motorSettings.shot_settings.id_target_flow.Value;
                float targetTimeOD = motorSettings.shot_settings.od_target_vol.Value / motorSettings.shot_settings.od_target_flow.Value;

                float pressureID = float.Parse(await App.ControllerManager.GetRegPressureSetpoint(sysID));
                float pressureOD = float.Parse(await App.ControllerManager.GetRegPressureSetpoint(sysOD));

                response = await App.ControllerManager.WaitBothRegPressures(10);
                response = await App.ControllerManager.DispenseToRing(
                    sysID,
                    targetTimeID,
                    xID,
                    tID,
                    sysOD,
                    targetTimeOD,
                    xOD,
                    tOD);

                Debug.Print(response);

                ResultsShotData shotData = App.ControllerManager.ParseDispenseResponse(response); // sets volumes, times, result pass/fail, message.
                // fill in the rest of the data:
                shotData.motor_type = motorName;
                shotData.id_valve_num = sysID;
                shotData.od_valve_num = sysOD;
                shotData.id_pressure = pressureID;
                shotData.od_pressure = pressureOD;

                string substance_id = motorSettings.shot_settings.id_sys_num == 1 ? settings.dispense_system.sys_1_contents : settings.dispense_system.sys_2_contents;
                string substance_od = motorSettings.shot_settings.od_sys_num == 1 ? settings.dispense_system.sys_1_contents : settings.dispense_system.sys_2_contents;

                if (shotData.shot_result == true)
                {
                    string tb = "  ";
                    Debug.Print("Dispense successful");
                    Debug.Print("Results:");
                    Debug.Print($"{tb}ID:");
                    Debug.Print($"{tb}{tb}Valve {motorSettings.shot_settings.id_sys_num} ({substance_id})");
                    Debug.Print($"{tb}{tb}Dispense volume: {shotData.id_vol:F3} mL ({shotData.id_vol.Value * 100 / motorSettings.shot_settings.id_target_vol.Value:F1}% of target)");
                    Debug.Print($"{tb}{tb}Dispense time: {shotData.id_time:F3} s");
                    Debug.Print($"{tb}{tb}Pressure: {shotData.id_pressure:F3} psi");
                    Debug.Print($"{tb}OD:");
                    Debug.Print($"{tb}{tb}Valve {motorSettings.shot_settings.id_sys_num} ({substance_od})");
                    Debug.Print($"{tb}{tb}Dispense volume: {shotData.od_vol:F3} mL ({shotData.od_vol.Value * 100 / motorSettings.shot_settings.od_target_vol.Value:F1}% of target)");
                    Debug.Print($"{tb}{tb}Dispense time: {shotData.od_time:F3} s");
                    Debug.Print($"{tb}{tb}Pressure: {shotData.od_pressure:F3} psi");
                }
                else
                {
                    Debug.Print($"Dispense failed: {shotData.shot_message}");
                    throw new Exception("Dispense failed");
                }

                // Move back to load for user inspection
                x = settings.ddm_common.load.x.Value;
                t = settings.ddm_common.load.t.Value;
                await App.ControllerManager.MoveJ(x, t);

                // Run calibration calculations
                float _sf1, _sf2;
                bool _calibSuccess;
                string _message;
                CalculateNewScaleFactors(shotData, settings, localData, out _calibSuccess, out _message, out _sf1, out _sf2);

                if (!_calibSuccess)
                {
                    throw new Exception("Calibration failed: Calculation unsuccessful");
                }

                // Return scale factors, success flag, message, and time
                result.time = DateTime.Now;
                result.motorName = motorName;
                result.sf1 = _sf1;
                result.sf2 = _sf2;
                result.message = "Success";
                result.success = true;

            }
            catch (Exception ex)
            {
                result.success = false;
                result.message = $"Error during calibration routine: {ex.Message}";
            }

            return result;
        }

        public static void CalculateNewScaleFactors(
            ResultsShotData prevShotData,
            CellSettings cellSettings,
            LocalData localData,

            out bool success,
            out string message,
            out float sf1,
            out float sf2)
        {


            /// <summary>
            /// Takes cell settings data, compares to the latest shot data, and
            /// estimates pressure adjustments required to improve shot volume accuracy for the next
            /// run. Neither saves nor validates calibration.
            /// 
            /// DOES NOT RUN THE ROBOT AROUND.
            /// 
            /// DOES NOT SAVE TO FILE.
            /// 
            /// </summary>

            success = false;
            message = String.Empty;
            sf1 = 1.00f;
            sf2 = 1.00f;
            CSShot targetShotData = null;
            LDMotorCalib calibOriginal = null;
            string tb = "  ";

            switch (prevShotData.motor_type)
            {
                case "ddm_57":
                    targetShotData = cellSettings.ddm_57.shot_settings;
                    calibOriginal = localData.calib_data.ddm_57;
                    break;
                case "ddm_95":
                    targetShotData = cellSettings.ddm_95.shot_settings;
                    calibOriginal = localData.calib_data.ddm_95;
                    break;
                case "ddm_116":
                    targetShotData = cellSettings.ddm_116.shot_settings;
                    calibOriginal = localData.calib_data.ddm_116;
                    break;
                case "ddm_170":
                    targetShotData = cellSettings.ddm_170.shot_settings;
                    calibOriginal = localData.calib_data.ddm_170;
                    break;
                case "ddm_170_tall":
                    targetShotData = cellSettings.ddm_170_tall.shot_settings;
                    calibOriginal = localData.calib_data.ddm_170_tall;
                    break;
            }

            LDMotorCalib calibNew = calibOriginal.Clone();

            Debug.Print($"Calculating scale factors based on motor size {prevShotData.motor_type}");

            // calculate real flow rate (from given shot data)
            // get target flow rate (from cell settings)
            // get calib data (from local data)
            // apply scale factor to flow rate lookup
            // verify new pressures are OK
            // copy new calib to local data and save to file

            float lastFlowID = prevShotData.id_vol.Value / prevShotData.id_time.Value;
            float targetFlowID = targetShotData.id_target_flow.Value;
            float sfID = targetFlowID / lastFlowID;
            float sysID = targetShotData.id_sys_num.Value;

            float lastFlowOD = prevShotData.od_vol.Value / prevShotData.od_time.Value;
            float targetFlowOD = targetShotData.od_target_flow.Value;
            float sfOD = targetFlowOD / lastFlowOD;
            float sysOD = targetShotData.od_sys_num.Value;

            if (sysID == sysOD)
            {
                switch (sysID)
                {
                    case 1: sf1 = (sfID + sfOD) / 2; break;
                    case 2: sf2 = (sfID + sfOD) / 2; break;
                }
            }
            else
            {
                sf1 = sysID == 1 ? sfID : sfOD;
                sf2 = sysID == 2 ? sfID : sfOD;
            }

            Debug.Print($"{tb}Individual scale factors calculated:");
            Debug.Print($"{tb}{tb}ID: {sfID:F3}");
            Debug.Print($"{tb}{tb}OD: {sfOD:F3}");
            Debug.Print($"{tb}Applying scale factors:");
            Debug.Print($"{tb}{tb}Sys 1: {sf1:F3}");
            Debug.Print($"{tb}{tb}Sys 2: {sf2:F3}");

            Debug.Print($"{tb}Updating calibration values:");
            calibNew.sys_1_pressure *= sf1;
            calibNew.sys_2_pressure *= sf2;
            Debug.Print($"{tb}{tb}Sys 1: ({calibNew.sys_1_pressure,5:0.000})");
            Debug.Print($"{tb}{tb}Sys 1: ({calibNew.sys_2_pressure,5:0.000})");
            //Debug.Print($"  Sys 1: ({calibNew.sys_1_flow:0.00}, {calibNew.sys_1_pressure,5:0.000})");
            //Debug.Print($"  Sys 1: ({calibNew.sys_2_flow:0.00}, {calibNew.sys_2_pressure,5:0.000})");


            // Basic validation

            // Check pressures against absolute limits

            bool validated = false;
            float sys1MaxPressure = cellSettings.dispense_system.sys_1_max_pressure.Value;
            float sys2MaxPressure = cellSettings.dispense_system.sys_2_max_pressure.Value;

            if (calibNew.sys_1_pressure > sys1MaxPressure || calibNew.sys_1_pressure < 0)
            {
                message = $"Calibration failed: System 1 pressure out of range ({calibNew.sys_1_pressure})";
                return;
            }
            if (calibNew.sys_2_pressure > sys2MaxPressure || calibNew.sys_2_pressure < 0)
            {
                message = $"Calibration failed: System 2 pressure out of range ({calibNew.sys_2_pressure})";
                return;
            }

            // Check pressures against relative limits

            float newPressure;
            float originalPressure;
            float diff;

            newPressure = calibNew.sys_1_pressure.Value;
            originalPressure = calibOriginal.sys_1_pressure.Value;
            diff = Math.Abs((newPressure - originalPressure) / originalPressure);

            if (diff > cellSettings.dispense_system.sys_1_max_pressure_dev_percent)
            {
                message = $"Validation failed: System 1 pressure deviated too far from calib ({diff})";
                return;
            }

            newPressure = calibNew.sys_1_pressure.Value;
            originalPressure = calibOriginal.sys_1_pressure.Value;
            diff = Math.Abs((newPressure - originalPressure) / originalPressure);

            if (diff > cellSettings.dispense_system.sys_2_max_pressure_dev_percent)
            {
                message = $"Validation failed: System 2 pressure deviated too far from calib ({diff})";
                return;
            }

            Debug.Print($"{tb}Calibration calculation successful");
            message = "Calibration calculation successful";
            success = true;
        }

        public void GenerateAndSaveCalibration(RunCalibResult result)
        {
            LocalData newLocalData = App.LocalDataManager.GetLocalData();

            newLocalData.calib_data.last_size = result.motorName;
            newLocalData.calib_data.last_calib = result.time;

            switch (result.motorName)
            {
                case "ddm_57":
                    newLocalData.calib_data.ddm_57.sys_1_pressure *= result.sf1;
                    newLocalData.calib_data.ddm_57.sys_2_pressure *= result.sf2;
                    break;
                case "ddm_95":
                    newLocalData.calib_data.ddm_95.sys_1_pressure *= result.sf1;
                    newLocalData.calib_data.ddm_95.sys_2_pressure *= result.sf2;
                    break;
                case "ddm_116":
                    newLocalData.calib_data.ddm_116.sys_1_pressure *= result.sf1;
                    newLocalData.calib_data.ddm_116.sys_2_pressure *= result.sf2;
                    break;
                case "ddm_170":
                    newLocalData.calib_data.ddm_170.sys_1_pressure *= result.sf1;
                    newLocalData.calib_data.ddm_170.sys_2_pressure *= result.sf2;
                    break;
                case "ddm_170_tall":
                    newLocalData.calib_data.ddm_170_tall.sys_1_pressure *= result.sf1;
                    newLocalData.calib_data.ddm_170_tall.sys_2_pressure *= result.sf2;
                    break;
            }

            App.LocalDataManager.SetLocalData(newLocalData);
            App.LocalDataManager.SaveLocalDataToFile();
        }

    }
}
