using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace DDMAutoGUI.utilities
{

    public class RunCalibResult
    {
        public bool success { get; set; }
        public string message { get; set; }
        public DateTime time { get; set; }
        public string motorName { get; set; }
        public float sf1 { get; set; }
        public float sf2 { get; set; }
    }


    public class FlowCalibrationManager
    {

        public FlowCalibrationManager() { }

        public async Task<RunCalibResult> RunCalibrationRoutineOnce(
            CellSettings settings,
            LocalData localData,
            string motorName)
        {

            /// <summary>
            /// Runs calibration routine for given motor size ONCE. Returns success flag and message.
            /// If successful, returns new pressure settings. Validates and saves to file if successful.
            /// Iteration handled in calling function if unsuccessful or if visual inspection fails.
            /// 
            /// RUNS THE ROBOT AROUND
            /// 
            /// </summary>

            RunCalibResult result = new RunCalibResult();

            result.success = false;
            result.message = "";

            try
            {
                float x, t;
                CSMotor motorSettings = App.SettingsManager.GetMotorSettingsFromName(motorName);

                // Enable power and home
                await App.ControllerManager.EnablePower();
                await App.ControllerManager.Home();

                // Move to load
                x = settings.ddm_common.load.x.Value;
                t = settings.ddm_common.load.t.Value;
                await App.ControllerManager.MoveJ(x, t);

                // Move to detect if correct CA catch tool is loaded
                x = motorSettings.calib_tool_test.x.Value;
                t = motorSettings.calib_tool_test.t.Value;
                await App.ControllerManager.MoveJ(x, t);

                // Get height to verify correct tool is loaded
                string response = await App.ControllerManager.MeasureHeightSingle();
                string[] responseArray = response.Split(" ");
                if (responseArray.Length < 2 || !float.TryParse(responseArray[1], out _))
                {
                    throw new Exception($"Calibration failed: Unexpected response format from height measurement: '{response}'"); // autogenerated... ?
                }
                float height = float.Parse(responseArray[1]);

                // Test height to verify correct tool is loaded
                float diffSurface = settings.calib_surface_height.Value - height;
                float diffTool = settings.calib_tool_height.Value - height;
                float diffMax = settings.calib_tool_max_diff.Value;

                if (Math.Abs(diffSurface) < diffMax)
                {
                    // if height is close to surface height, no tool is loaded
                    throw new Exception($"Calibration failed: No tool detected");
                }
                else if (Math.Abs(diffTool) < diffMax)
                {
                    // if height is close to tool height, correct tool is loaded and continue with calibration
                }
                else
                {
                    // if height is not close to either, something else is wrong, abort
                    throw new Exception($"Calibration failed: Unexpected height measurement ({height})");
                }

                // Set pressures based on current calib
                LDCalib calib = App.LocalDataManager.GetCalibFromMotorName(localData, motorName);
                float _pressure1 = calib.sys_1_pressure.Value;
                float _pressure2 = calib.sys_2_pressure.Value;
                if (_pressure1 != null)
                {
                    Debug.Print($"Setting pressure for system 1 ({settings.dispense_system.sys_1_contents}) to {_pressure1:F3} psi");
                    response = await App.ControllerManager.SetRegPressure(1, _pressure1);
                }
                else
                {
                    Debug.Print($"No pressure change for system 1 ({settings.dispense_system.sys_1_contents})");
                }
                if (_pressure2 != null)
                {
                    Debug.Print($"Setting pressure for system 2 ({settings.dispense_system.sys_2_contents}) to {_pressure2:F3} psi");
                    response = await App.ControllerManager.SetRegPressure(2, _pressure2);
                }
                else
                {
                    Debug.Print($"No pressure change for system 2 ({settings.dispense_system.sys_2_contents})");
                }
                Debug.Print("Waiting for pressures to settle...");
                response = await App.ControllerManager.WaitBothRegPressures(10);
                await Task.Delay(1000);
                Debug.Print("Pressures settled");
                Debug.Print("Zeroing flow sensors...");
                response = await App.ControllerManager.SetZeroShift(3);
                Debug.Print("Flow sensors zeroed");
                Debug.Print("Pressures set");

                // Dispense to ring
                int sysID = motorSettings.shot_settings.id_sys_num.Value;
                int sysOD = motorSettings.shot_settings.od_sys_num.Value;
                float xID = motorSettings.id_disp.x.Value;
                float tID = motorSettings.id_disp.t.Value;
                float xOD = motorSettings.od_disp.x.Value;
                float tOD = motorSettings.od_disp.t.Value;
                float targetTimeID = motorSettings.shot_settings.id_target_vol.Value / motorSettings.shot_settings.id_target_flow.Value;
                float targetTimeOD = motorSettings.shot_settings.od_target_vol.Value / motorSettings.shot_settings.od_target_flow.Value;

                float pressureID = float.Parse(await App.ControllerManager.GetRegPressureSetpoint(sysID));
                float pressureOD = float.Parse(await App.ControllerManager.GetRegPressureSetpoint(sysOD));

                response = await App.ControllerManager.WaitBothRegPressures(10);
                response = await App.ControllerManager.DispenseToRing(
                    sysID,
                    targetTimeID,
                    xID,
                    tID,
                    sysOD,
                    targetTimeOD,
                    xOD,
                    tOD);

                Debug.Print(response);

                ResultsShotData shotData = App.ControllerManager.ParseDispenseResponse(response); // sets volumes, times, result pass/fail, message
                // fill in the rest of the data:
                shotData.motor_type = motorName;
                shotData.id_valve_num = sysID;
                shotData.od_valve_num = sysOD;
                shotData.id_pressure = pressureID;
                shotData.od_pressure = pressureOD;

                string substance_id = motorSettings.shot_settings.id_sys_num == 1 ? settings.dispense_system.sys_1_contents : settings.dispense_system.sys_2_contents;
                string substance_od = motorSettings.shot_settings.od_sys_num == 1 ? settings.dispense_system.sys_1_contents : settings.dispense_system.sys_2_contents;

                if (shotData.shot_result == true)
                {
                    string tb = "  ";
                    Debug.Print("Dispense successful");
                    Debug.Print("Results:");
                    Debug.Print($"{tb}ID:");
                    Debug.Print($"{tb}{tb}Valve {motorSettings.shot_settings.id_sys_num} ({substance_id})");
                    Debug.Print ($"{tb}{tb}Dispense volume: {shotData.id_vol:F3} mL ({shotData.id_vol.Value * 100 / motorSettings.shot_settings.id_target_vol.Value:F1}% of target)");
                    Debug.Print($"{tb}{tb}Dispense time: {shotData.id_time:F3} s");
                    Debug.Print($"{tb}{tb}Pressure: {shotData.id_pressure:F3} psi");
                    Debug.Print($"{tb}OD:");
                    Debug.Print($"{tb}{tb}Valve {motorSettings.shot_settings.id_sys_num} ({substance_od})");
                    Debug.Print($"{tb}{tb}Dispense volume: {shotData.od_vol:F3} mL ({shotData.od_vol.Value * 100 / motorSettings.shot_settings.od_target_vol.Value:F1}% of target)");
                    Debug.Print($"{tb}{tb}Dispense time: {shotData.od_time:F3} s");
                    Debug.Print($"{tb}{tb}Pressure: {shotData.od_pressure:F3} psi");
                }
                else
                {
                    Debug.Print($"Dispense failed: {shotData.shot_message}");
                    throw new Exception("Dispense failed");
                }

                // Move back to load for user inspection
                x = settings.ddm_common.load.x.Value;
                t = settings.ddm_common.load.t.Value;
                await App.ControllerManager.MoveJ(x, t);

                // Run calibration calculations and save if successful
                float _sf1, _sf2;
                bool _calibSuccess;
                CalibratePressures(shotData, settings, localData, out _calibSuccess, out _sf1, out _sf2);

                if (!_calibSuccess)
                {
                    throw new Exception("Calibration failed: Calculation unsuccessful");
                }

                // Return scale factors and success flag
                result.sf1 = _sf1;
                result.sf2 = _sf2;
                result.motorName = motorName;
                result.message = "Success";
                result.success = true;

            }
            catch (Exception ex)
            {
                result.success = false;
                result.message = $"Error during calibration routine: {ex.Message}";
            }

            return result;
        }

        public static void CalibratePressures(
            ResultsShotData prevShotData,
            CellSettings cellSettings,
            LocalData localData,

            out bool success,
            out float sf1,
            out float sf2)
        {


            /// <summary>
            /// Takes cell settings data, compares to the latest shot data, and
            /// estimates pressure adjustments required to improve shot volume accuracy for the next
            /// run. If new calib looks OK, new calib is copied into local data and saved to file.
            /// 
            /// DOES NOT RUN THE ROBOT AROUND
            /// 
            /// </summary>

            success = false;
            CSShot targetShotData = null;
            LDCalib calibOriginal = null;
            string tb = "  ";

            switch (prevShotData.motor_type)
            {
                case "ddm_57":
                    targetShotData = cellSettings.ddm_57.shot_settings;
                    calibOriginal = localData.ddm_57;
                    break;
                case "ddm_95":
                    targetShotData = cellSettings.ddm_95.shot_settings;
                    calibOriginal = localData.ddm_95;
                    break;
                case "ddm_116":
                    targetShotData = cellSettings.ddm_116.shot_settings;
                    calibOriginal = localData.ddm_116;
                    break;
                case "ddm_170":
                    targetShotData = cellSettings.ddm_170.shot_settings;
                    calibOriginal = localData.ddm_170;
                    break;
                case "ddm_170_tall":
                    targetShotData = cellSettings.ddm_170_tall.shot_settings;
                    calibOriginal = localData.ddm_170_tall;
                    break;
            }

            LDCalib calibNew = calibOriginal.Clone();

            Debug.Print($"Calculating scale factors based on motor size {prevShotData.motor_type}");



            // calculate real flow rate (from given shot data)
            // get target flow rate (from cell settings)
            // get calib data (from local data)
            // apply scale factor to flow rate lookup
            // verify new pressures are OK
            // copy new calib to local data and save to file

            float lastFlowID = prevShotData.id_vol.Value / prevShotData.id_time.Value;
            float targetFlowID = targetShotData.id_target_flow.Value;
            float sfID = targetFlowID / lastFlowID;
            float sysID = targetShotData.id_sys_num.Value;

            float lastFlowOD = prevShotData.od_vol.Value / prevShotData.od_time.Value;
            float targetFlowOD = targetShotData.od_target_flow.Value;
            float sfOD = targetFlowOD / lastFlowOD;
            float sysOD = targetShotData.od_sys_num.Value;



            // default to 1.0 (no scaling)
            sf1 = 1f;
            sf2 = 1f;

            if (sysID == sysOD)
            {
                switch (sysID)
                {
                    case 1: sf1 = (sfID + sfOD) / 2; break;
                    case 2: sf2 = (sfID + sfOD) / 2; break;
                }
            }
            else
            {
                sf1 = sysID == 1 ? sfID : sfOD;
                sf2 = sysID == 2 ? sfID : sfOD;
            }

            Debug.Print($"{tb}Individual scale factors calculated:");
            Debug.Print($"{tb}{tb}ID: {sfID:F3}");
            Debug.Print($"{tb}{tb}OD: {sfOD:F3}");
            Debug.Print($"{tb}Applying scale factors:");
            Debug.Print($"{tb}{tb}Sys 1: {sf1:F3}");
            Debug.Print($"{tb}{tb}Sys 2: {sf2:F3}");

            Debug.Print($"{tb}Updating calibration values:");
            calibNew.sys_1_pressure *= sf1;
            calibNew.sys_2_pressure *= sf2;
            Debug.Print($"{tb}{tb}Sys 1: ({calibNew.sys_1_pressure,5:0.000})");
            Debug.Print($"{tb}{tb}Sys 1: ({calibNew.sys_2_pressure,5:0.000})");
            //Debug.Print($"  Sys 1: ({calibNew.sys_1_flow:0.00}, {calibNew.sys_1_pressure,5:0.000})");
            //Debug.Print($"  Sys 1: ({calibNew.sys_2_flow:0.00}, {calibNew.sys_2_pressure,5:0.000})");







            // CHECK PRESSURES AGAINST ABSOLUTE LIMITS

            float sys1MaxPressure = cellSettings.dispense_system.sys_1_max_pressure.Value;
            float sys2MaxPressure = cellSettings.dispense_system.sys_2_max_pressure.Value;

            if (calibNew.sys_1_pressure > sys1MaxPressure || calibNew.sys_1_pressure < 0)
            {
                Debug.Print($"{tb}Calibration failed: System 1 pressure out of range ({calibNew.sys_1_pressure})");
                success = false;
                return;
            }
            if (calibNew.sys_2_pressure > sys2MaxPressure || calibNew.sys_2_pressure < 0)
            {
                Debug.Print($"{tb}Calibration failed: System 2 pressure out of range ({calibNew.sys_2_pressure})");
                success = false;
                return;
            }





            // CHECK PRESSURES AGAINST RELATIVE LIMITS (DRIFTING TOO FAR FROM ORIGINAL CALIBRATION)

            float newPressure;
            float originalPressure;
            float diff;

            newPressure = calibNew.sys_1_pressure.Value;
            originalPressure = calibOriginal.sys_1_pressure.Value;
            diff = Math.Abs((newPressure - originalPressure) / originalPressure);

            if (diff > cellSettings.dispense_system.sys_1_max_pressure_dev_percent)
            {
                Debug.Print($"{tb}Calibration failed: System 1 pressure deviated too far from calib ({diff})");
                success = false;
                return;
            }

            newPressure = calibNew.sys_1_pressure.Value;
            originalPressure = calibOriginal.sys_1_pressure.Value;
            diff = Math.Abs((newPressure - originalPressure) / originalPressure);

            if (diff > cellSettings.dispense_system.sys_2_max_pressure_dev_percent)
            {
                Debug.Print($"{tb}Calibration failed: System 2 pressure deviated too far from calib ({diff})");
                success = false;
                return;
            }



            // If checks pass, copy new calib data to local data

            switch (prevShotData.motor_type)
            {
                case "ddm_57":
                    localData.ddm_57 = calibNew.Clone();
                    break;
                case "ddm_95":
                    localData.ddm_95 = calibNew.Clone();
                    break;
                case "ddm_116":
                    localData.ddm_116 = calibNew.Clone();
                    break;
                case "ddm_170":
                    localData.ddm_170 = calibNew.Clone();
                    break;
                case "ddm_170_tall":
                    localData.ddm_170_tall = calibNew.Clone();
                    break;
            }

            Debug.Print($"{tb}Calibration successful, new calibration saved to local data.");

            App.LocalDataManager.SaveLocalDataToFile();
            success = true;
        }

    }
}
