using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Diagnostics;

namespace DDMAutoGUI.Utilities
{
    public class OCRData
    {
        public OCRMetadata metadata { get; set; }
        public OCRTiming[] timings { get; set; }
        public List<OCRResult> results { get; set; }
    }

    public class OCRMetadata
    {
        public DateTime start_time { get; set; }
        public float total_time_seconds { get; set; }
        public int image_count { get; set; }
    }

    public class OCRTiming
    {
        public string file { get; set; }
        public float compress_time_seconds { get; set; }
        public float ocr_time_seconds { get; set; }
    }

    public class OCRResult
    {
        public string file { get; set; }
        public List<OCRString> strings { get; set; }
    }

    public class OCRString
    {
        public string text { get; set; }
        public float score { get; set; }
    }

    public static class OCRManagerExtensions
    {
        public static string GetBestResultForFile(this OCRData ocrData, string fileName)  // .... autogenerated
        {
            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                var bestString = result.strings.OrderByDescending(s => s.score).First();
                return bestString.text;
            }
            return null;
        }


        public static string GetToolType(this OCRData ocrData, string fileName)
        {
            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                if (result.strings.Any(s => s.text.StartsWith("57-")))
                {
                    return "ddm_57";
                }
                else if (result.strings.Any(s => s.text.StartsWith("95-")))
                {
                    return "ddm_95";
                }
                else if (result.strings.Any(s => s.text.StartsWith("116-")))
                {
                    return "ddm_116";
                }
                else if (result.strings.Any(s => s.text.StartsWith("170-")))
                {
                    return "ddm_170";
                }

                // 170 tall ?
            }
            return null;
        }


        public static string GetToolSN(this OCRData ocrData, string motorName, string fileName)
        {
            string toolPrefix = "";

            switch (motorName)
            {
                case "ddm_57":
                    toolPrefix = "57-";
                    break;
                case "ddm_95":
                    toolPrefix = "95-";
                    break;
                case "ddm_116":
                    toolPrefix = "116-";
                    break;
                case "ddm_170":
                    toolPrefix = "170-";
                    break;
                case "ddm_170_tall":

                    // ?

                    break;
            }

            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                var snString = result.strings.Where(s => s.text.StartsWith(toolPrefix));
                if (snString != null)
                {
                    if (snString.Count() > 0) return snString.First().text;
                }
                else
                {
                    Debug.Print($"Could not find string with correct prefix {toolPrefix})");
                }
            }
            return null;
        }


        public static string GetRingSN(this OCRData ocrData, string motorName, string fileName)
        {
            int snLength = 0;

            switch (motorName)
            {
                case "ddm_57":
                    break;
                case "ddm_95":
                    break;
                case "ddm_116":
                    snLength = 12;
                    break;
                case "ddm_170":
                    break;
                case "ddm_170_tall":
                    break;
            }

            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                var snString = result.strings.Where(s => s.text.Length == snLength);
                if (snString != null)
                {
                    if (snString.Count() > 0 && snString.First().text.Contains("TW"))
                    {
                        return snString.First().text;
                    }
                    else
                    {
                        Debug.Print("Could not find 'TW' in string of correct length");
                    }
                }
                else
                {
                    Debug.Print($"Could not find string of correct length ({snLength})");
                }
            }
            return null;
        }
    }



}