using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace DDMAutoGUI.Utilities
{

    public class OCRData
    {
        public List<OCRResult> results { get; set; }
    }

    public class OCRResult
    {
        public string file { get; set; }
        public List<OCRString> strings { get; set; }
    }

    public class OCRString
    {
        public string text { get; set; }
        public float score { get; set; }
    }



    public class OCRManager
    {

        public static string ocrScriptName = "process_images.py";
        public static string ocrOutputFileName = "OCRResults.json";

        public string ocrScriptPath;
        //public string ocrInputFolder;
        //public string ocrOutputFile;

        public OCRManager()
        {
            string appDir = AppContext.BaseDirectory;
            ocrScriptPath = System.IO.Path.Combine(appDir, "Utilities", "Vision", ocrScriptName);
            //ocrInputFolder = System.IO.Path.Combine(appDir, "acquisitions");
            //ocrOutputFile = System.IO.Path.Combine(appDir, "acquisitions", ocrOutputFileName);
        }



        public async Task<OCRData> RunOCR(string imageInputFolder)
        {
            string ocrOutputFile = System.IO.Path.Combine(imageInputFolder, ocrOutputFileName);

            await Task.Run(() =>
            {
                string arguments =
                    $"\"{ocrScriptPath}\" " +
                    $"--input-folder \"{imageInputFolder}\" " +
                    $"--output-file \"{ocrOutputFile}\"" +
                    $"--factor 4";

                var startInfo = new ProcessStartInfo
                {
                    FileName = "python",
                    Arguments = arguments,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    CreateNoWindow = true
                };

                using (var process = new Process())
                {
                    process.StartInfo = startInfo;
                    process.OutputDataReceived += (s, e) =>
                    {
                        if (!string.IsNullOrWhiteSpace(e.Data))
                            Debug.WriteLine(e.Data);
                    };

                    process.ErrorDataReceived += (s, e) =>
                    {
                        if (!string.IsNullOrWhiteSpace(e.Data))
                            Debug.WriteLine("ERR: " + e.Data);
                    };

                    process.Start();
                    process.BeginOutputReadLine();
                    process.BeginErrorReadLine();
                    process.WaitForExit();

                    int exitCode = process.ExitCode;
                    Debug.WriteLine($"Python process exited with code {exitCode}");
                }
            });

            string fileContent = File.ReadAllText(ocrOutputFile);

            OCRData ocrData = System.Text.Json.JsonSerializer.Deserialize<OCRData>(fileContent);
            return ocrData;
        }
    }

    public static class OCRManagerExtensions
    {
        public static string GetBestResultForFile(this OCRData ocrData, string fileName)  // .... autogenerated
        {
            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                var bestString = result.strings.OrderByDescending(s => s.score).First();
                return bestString.text;
            }
            return null;
        }


        public static string GetToolType(this OCRData ocrData, string fileName)
        {
            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                if (result.strings.Any(s => s.text.Contains("57")))
                {
                    return "ddm_57";
                }
                else if (result.strings.Any(s => s.text.Contains("95")))
                {
                    return "ddm_95";
                }
                else if (result.strings.Any(s => s.text.Contains("116")))
                {
                    return "ddm_116";
                }
                else if (result.strings.Any(s => s.text.Contains("170")))
                {
                    return "ddm_170";
                }
            }
            return null;
        }


        public static string GetToolSN(this OCRData ocrData, string motorName, string fileName)
        {
            string toolPrefix = "";

            switch (motorName)
            {
                case "ddm_57":
                    break;
                case "ddm_95":
                    break;
                case "ddm_116":
                    toolPrefix = "116";
                    break;
                case "ddm_170":
                    break;
                case "ddm_170_tall":
                    break;
            }

            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                var snString = result.strings.Where(s => s.text.StartsWith(toolPrefix));
                if (snString != null)
                {
                    if (snString.Count() > 0) return snString.First().text;
                }
                else
                {
                    Debug.Print($"Could not find string with correct prefix {toolPrefix})");
                }
            }
            return null;
        }


        public static string GetRingSN(this OCRData ocrData, string motorName, string fileName)
        {
            int snLength = 0;

            switch (motorName)
            {
                case "ddm_57":
                    break;
                case "ddm_95":
                    break;
                case "ddm_116":
                    snLength = 12;
                    break;
                case "ddm_170":
                    break;
                case "ddm_170_tall":
                    break;
            }

            var result = ocrData.results.FirstOrDefault(r => r.file == fileName);
            if (result != null && result.strings.Count > 0)
            {
                var snString = result.strings.Where(s => s.text.Length == snLength);
                if (snString != null)
                {
                    if (snString.Count() > 0 && snString.First().text.Contains("TW"))
                    {
                        return snString.First().text;
                    }
                    else
                    {
                        Debug.Print("Could not find 'TW' in string of correct length");
                    }
                }
                else
                {
                    Debug.Print($"Could not find string of correct length ({snLength})");
                }
            }
            return null;
        }
    }

}

